### PR TITLE
Datetimepicker consistency fix, widget creation, localization and nitpicks

### PR DESCRIPTION
**Pull request by SpeedyD**
- Added Month and Year selection
- Made 'datepicker' consistenty be the class, as there are sometimes multiple pickers on a page.
- Made the 'datepicker' function a widget.
- Added localization, clicking Now will return site time rather than the time of the PC used.

- For some reason, the cooldown datepicker on a character's stats modal did not work, would not work, whatever- so I have done a lot of specific fixes just for that one.

This has been thoroughly tested and seems to be working fine now.

### CODE REVIEW

**Comment by SpeedyD** [comment]
🤦
I make the filename consistent in code and then forget to change the actual filename X_x

**Comment by SpeedyD** [comment]
.... don't approve just yet. Realized a stupid issue. I should've made it CLASS consistent, cause I realize now that I forgot to test when there's multiple datetimepickers, and IDs block that.

Be back after extensive tests.

**Comment by SpeedyD** [comment]
..for the record, I do NOT understand what the blade formatter is doing, but whatever

**Comment by SpeedyD** [comment]
It has been thoroughly checked - and I'm.. exceedingly confused why the stats modal's datepicker didn't work.

I _got_ it to work, but why DIDN'T it??

**Review by itinerare — APPROVED** [review]

**Comment by SpeedyD** [comment]
...oh yeah, with my other PR just pushed through, this one doesn't need that script section at all! Yay!

**Comment by AW0005** [comment]
https://github.com/SpeedyD/lorekeeper/pull/213

Little update coming through to keep the datepicker floaty while using it's "inline" setting

**Comment by SpeedyD** [comment]
Absolutely, love that, thanks @AW0005!

**Comment by SpeedyD** [comment]
@itinerare why is the formatter doing that weird spacing to one of the js lines? I purposely reverted it to the last part being part of the previous line. . . 

And NOW the final change is that it put it back on ONE line??? I do not understand the blade formatter / lint / whatever's rules.

**Comment by itinerare** [comment]
Would that I could help you, but the blade formatter is not any less of a mystery to me sometimes...

**Review by Ne-wt — APPROVED** [review]

**Pull request merged**
