### PR TITLE
Feature/comment sorting

### PR DESCRIPTION
**Pull request by ScuffedNewt**
Adds comment sorting to comments & also tidies up some minor things
(I will eventually get my grubby hands on a proper comment refactor)

### CODE REVIEW

**Review by itinerare — APPROVED** [review]

**Review by SpeedyD — COMMENTED** [review]
I'd like to approve this, but is it finished? More changes were added after the last approval, so I'm concerned about it getting merged in too early...

**Review by itinerare — APPROVED** [review]

**Comment by SpeedyD** [comment]
> There were some bugs found (and fixed) pretty shortly after, iirc.

If it's just that, then I'll hit approve, but I'd like @ScuffedNewt to confirm this first. :S

**Comment by ScuffedNewt** [comment]
@SpeedyD yep this is all good to go

**Comment by SpeedyD** [comment]
> @SpeedyD yep this is all good to go

Then allow me to fully approve this.

**Review by SpeedyD — APPROVED** [review]

**Pull request merged**
