### PR TITLE
Feat: allow items to use built-in rarities instead of individual system

### PR DESCRIPTION
**Pull request by ScuffedNewt**
#1113 

tested loot conditionals etc also

### CODE REVIEW

**Comment by itinerare** [comment]
I think my one worry is that it might not be obvious what correlates to what wrt conditional loot tables, and/or that, if it's by sort, adjusting the sort without thinking to adjust the loot tables could have unintended adverse affects. Which is to say, I don't think tying it to something that can change without the end user really realizing it is wise....

**Comment by ScuffedNewt** [comment]
I think that a small alert appearing next to the sort of any conditional tables exist could be a decent compromise, I think an alert on loot tables may go unnoticed by themselves but with both it could be a decent solution

otherwise do you have another idea for how to let the site admins know ?

**Comment by itinerare** [comment]
Displayed when sorting rarities, you mean?

**Comment by ScuffedNewt** [comment]
yeah I meant if any conditional table not of lol

**Comment by itinerare** [comment]
Haha, yeah, gotcha.
Anyhow, that would probably work-- agreed that I don't think an alert by loot tables would do much.... 

I think it'd also be necessary to display the sort value for each rarity somewhere (perhaps also on the rarity index for quick/easy ref) so that admins know what to set conditional table value(s) to.

**Comment by ScuffedNewt** [comment]
they don't have to set it to a number, they set it to the rarity itself

**Comment by ScuffedNewt** [comment]
I think you misunderstood the setup! in which case I think the sort alert is also unneeded ?

**Comment by itinerare** [comment]
Ahhh, I was remembering conditional loot tables just having you punch in a number. All good, then.

**Review by itinerare — APPROVED** [review]

**Comment by itinerare** [comment]
That being said, I don't think just adding a small note of [changing sort order significantly may impact conditional tables] or somesuch would go amiss.

**Review by SpeedyD — APPROVED** [review]
Yeah, I'm gonna be honest, never understood why there was a numeric rarity system for items. I approve, vastly, of this change.

**Comment by itinerare** [comment]
Realized that there needs to be some means of shuffling existing item rarities over to the new setup as well... ideally one that's reasonably easy to adjust.

**Review by SpeedyD — APPROVED** [review]

**Review by itinerare — APPROVED** [review]
Oh, I like that solution for converting existing rarities a *lot*, well done.

**Pull request merged**
