### PR TITLE
Add Extra / Nice-To-Have Filters

### PR DESCRIPTION
**Pull request by ScuffedNewt**
Adds some filters around the site! 
This is marked as ready, but ideally would be home to some discussion / conversation about areas that might need some filters!
Lorekeeper is a bit of a beast as is, but funnily enough, does not have a consistent coverage of filtering

**Areas Added Thus Far:**
- User and character inventories
- User submissions
- Loottables (admin panel)

### CODE REVIEW

**Review by SpeedyD — COMMENTED** [review]
Looks good at first glance, will give this a more solid review (and likely approval) when I got more time ^^;;

**Review by SpeedyD — APPROVED** [review]

**Review by SpeedyD — APPROVED** [review]
...yeah, I looked it over thoroughly and I STILL missed the fact that $artists wasn't defined. =_=;;

Eesh.. Good job catching and fixing that, Newt. Reapproved.

**Review by itinerare — APPROVED** [review]

**Comment by itinerare** [comment]
Checking in with this one-- are you interested in adding more onto it, or should I just go ahead and merge?

**Comment by ScuffedNewt** [comment]
I didnt think of any more myself, and I don't think anymore where suggested, so I think this is fine to merge as-is and if more search filters are requested down the line it should be easy to add in another PR!

**Comment by itinerare** [comment]
Makes sense to me!

**Pull request merged**
