### PR TITLE
fix(subtypes): stop error on slots

### PR DESCRIPTION
**Pull request by ScuffedNewt**

### CODE REVIEW

**Comment by SpeedyD** [comment]
.....Um, sorry, but what does this actually fix? Seems more like it's removing functionality.

**Comment by ScuffedNewt** [comment]
it fixes the slot tag 
if you view the code the subtypes are treated differently further done, this code is unneeded since the subtype IDs are not contained in the character image

**Comment by ScuffedNewt** [comment]
you can test it yourself to see, but I had a few big reports across multiple sites - this has fixed it

**Comment by SpeedyD** [comment]
Right, fair enough. I think this error is primarily caused by the fact that that slot tags haven't been converted as did Design Updates and Character images, though new & edited slots shouldn't have this issue altogether.

On the other hand, the code does seem superfluous, as it's a relation now. It may be an issue for sites who have hard-coded a check for which image to use on subtypes, but that requires at most a check to fix.

**Review by SpeedyD — APPROVED** [review]

**Review by itinerare — APPROVED** [review]

**Pull request merged**
